title: Maria Dancianu # your name (or website title) here
logo: "/images/maria_cv.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Milan, Italy
  <br><br>
  <a href="https://it.linkedin.com/in/maria-dancianu-860613146/en">View My LinkedIn Profile</a>   
  <br><br>
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
